### ISSUE TITLE
Bug in Code for Testing

### ISSUE THREAD

**Issue by rudenko-gold** [Costello1329/made-cpp-2020-hw#26]
[Line 88 in test.cpp](https://github.com/Costello1329/made-cpp-2020-hw/blob/hw_4_matrix/matrix/test/test.cpp)

```
        auto partial = mat1[1];
        partial[1] = 400.;

        ASSERT_TRUE_MSG(mat1[1][1] == 400., "Operator []")
```

`partial` is a non-reference value here, so the test works incorrectly

Can be fixed by adding `&` after `auto` key-word

**Comment by senior-sigan** [comment]
@rudenko-gold partial should not be a reference value. The type of `mat1[1]` should implement somehow the behavior `partial[1] = 400.`. In the task's description, you can see a hint.

> Чтобы реализовать семантику [][] понадобится прокси-класс. Оператор матрицы возращает другой класс, в котором тоже используется оператор [] и уже этот класс возвращает значение.

Maybe I'm not supposed to comment on this issue. But I hope it helps other students somehow and allows teachers to close this issue if I'm not wrong here.

**Comment by rudenko-gold** [comment]
@senior-sigan the proxy class contains a pointer to memory with data, if we want to make a copy of this class (in your case), we should copy the whole data of row, because in another case we have two pointers to the same data and will get undefined behavior trying to delete already deleted memory area. Anyway, copying the whole row is a very expensive action, so we can use a smart pointer in implementation (but this topic haven't covered yet in this course) or return proxy class as a reference value to maintain the integrity of data and make proxy-class uncopyable (like unique_ptr).

**Comment by dshatov** [comment]
Fortunately, we do not need to free the memory allocated for the whole matrix or for the matrix row when the proxy instance is destroyed.

When instantiating a proxy, we should not transfer nor share ownership of the matrix data to that proxy.

The only potential danger in this case is that working with a proxy can lead to undefined behavior after the destruction of the matrix.

You just need to emphasize in the documentation that working with a proxy instance outside the lifetime of a matrix instance leads to undefined behavior.
